### PR TITLE
Change some double quotes to single quotes

### PR DESCRIPTION
**Pull request by honzi**
https://www.drupal.org/coding-standards#quotes recommends single quotes by default, so I changed a few. I excluded strings that involve `@something`'s and strings that would need to be changed (e.g. `'` to `\'`) for now.

### CODE REVIEW

**Comment by bwood** [comment]
Hi @honzi,

If you're looking for other things to do... :-) ...I could use help with evaluating [solutions for automatically adding an anchor-linked table of contents](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=github%20markdown%20table%20of%20contents) to the README.  The TOC that's there was done manually, and some of the anchor links are broken.

Best,
Brian

**Comment by honzi** [comment]
Sure, challenge accepted! I'll see what I can do.

**Comment by honzi** [comment]
I found a Chrome userscript at https://github.com/tomancaklab/tomancaklab.github.io/blob/master/gfm-add-toc.user.js that seems to generate an accurate TOC for markdown files. It's limited to the wysiwyg editor for GitHub repository wiki files, as that seems to be drastically different from the wysiwyg editor for files within the repository. Copying and pasting the `README.md` file into a wiki file editor will generate a pretty accurate TOC that can be copypasted back into the `README.md` file. I'll try to create a Chrome extension that does this for all GitHub files, but the complex editor that GitHub uses for repository files may be too complex.

**Comment by bwood** [comment]
@honzi Thanks for your research thus far!  Let's continue discussion in [this issue](https://github.com/bwood/ucberkeley_cas-7/issues/43).

**Comment by bwood** [comment]
Hi @honzi.

I just wanted to mention a syntax error that crept in as the result of this PR.  (My bad for not catching it before merging.) When changing `"` to `'`, make sure that any `'` in the double-quoted line are escaped.

```
$ git blame -L 48,52 ucberkeley_cas.module
48cfd579 (Brian Wood 2014-07-09 17:30:51 -0700 48)     case 'cas_add_user_form':
0237a82d (Jan Horava 2015-10-14 20:43:18 -0700 49)       $form['account']['cas_name_txt']['#markup'] = 'To find the CAS User ID for a UC Berkeley employee visit the ' . l('CalNet Directory', 'https://calnet.berkeley.edu/directory/index.pl', array('attributes' => array('target'=>'_blank'))) . ' and search for the person.  In your search results click on the person's name. At the top of the page you should see <em>Details for Jane Smith (UID: 111111)</em>. Copy that UID number and paste it into the CAS User ID box.';
0237a82d (Jan Horava 2015-10-14 20:43:18 -0700 50)       $form['account']['cas_name']['#title'] = 'CAS User ID';
0237a82d (Jan Horava 2015-10-14 20:43:18 -0700 51)       $form['account']['cas_name']['#description'] = 'In order to create a new CalNet (CAS) authenticated user, just enter the person's CAS UID here. ' . $form['account']['cas_name']['#description'];
48cfd579 (Brian Wood 2014-07-09 17:30:51 -0700 52)       break;
```

If you're not using an editor that highlights php syntax errors, you can always use `php -l` to check files before committing.

Here's the easy fix: https://github.com/bwood/ucberkeley_cas-7/commit/ee63b295433e2532a0952d97e45bb1cfb1b77558

**Comment by honzi** [comment]
Ack, sorry about that. Not quite sure how I missed that, but I'll be more careful.

**Pull request merged**
